width = 80
header = "="*width
divider = '-'*width
char = "Characteristics"
side = "|"
charWs = " WS "
charBs = " BS "
charS = "  S "
charT = "  T "
charAg = " AG "
charInt = " Int "
charFel = " Fel "
charWp = " WP "
charPer = " Per "
charCorr = " Cor "
charIns = " Ins "
charPsy = " Psy "
charFate = " Ft "
charRace = " Race  "
CharacteristicsHeaderLine = side+charRace+side+charWs+side+charBs+side+charS+side+charT+side+charAg+side+charInt+side+charPer+side+charWp+side+charFel+side+charFate+side+charCorr+side+charIns+side+charPsy+side
